<?php
$this -> title = "Add new book"; 
$this -> headTitle($this -> title);

?>
<html>
<body>
<head>
<?php echo $this->headScript()->prependFile($this->baseUrl().'/js/book.js'); ?>
</head>
<?php

$booksid = isset($_GET['id']) && is_numeric($_GET['id'])?intval($_GET['id']):0; 

$books = new Application_Model_DbTable_Books(); 
$book = $books -> fetchAll($books -> select()-> where('id = ?', $booksid)); 
foreach ($book as $book1) 
{?> 

 <input type = "hidden" name = "id" id = "idbook" value = "<?=$book1['id']?>"/>  
 
 <label > Name </label >  
 <input class = "form-control namebook" id = "namebook" type = "text" name = "name" value = "<?=$book1['name']?>"
 placeholder = "name" required />

 <label> Author </label >  
 <select class = "form-control"name = "author"id = "authorbook"required >  
 <option value = "0" >  .  .  .  </option >  <?php
$author = new Application_Model_DbTable_Authors; 
$showlist = $author -> fetchAll(); 

foreach ($showlist as $authors) {?>  <option value = '<?=$authors['id']?>' <?php
if ($authors['id'] == $book1['authorid']) {
echo 'selected'; 
}?>  >  <?= $authors['name']?>  </option >  <?php
}?>  </select >  

<label > category </label >   </br>
<select class = "category_select" name = "category[]"id = "category"title = "Choose of the categories ..."multiple >  <?php
$Categories = new Application_Model_DbTable_Categories(); 
$showlist = $Categories -> fetchAll(); 
foreach ($showlist as $categories) {?>  
<option value = '<?=$categories['id']?>' <?php
$CategoriesBook = new Application_Model_DbTable_CategoriesBook(); 
$categoriesbook = $CategoriesBook -> fetchAll(); 
$count = count($categoriesbook); 

for ($i = 0; $i < $count; $i++) {
if ($categories['id'] == $categoriesbook[$i]['idcategories'] && $categoriesbook[$i]['idbook'] == $book1['id']) {
echo 'selected'; 
}
}?>  ><?= $categories['name']?>  </option >  <?php
}?>  </select >   </br>

<label> descrabtion </label >  
<input class = "form-control decbook" id = "decbook" type = "text" name = "descrabtion" value = "<?=$book1['descrabtion']?>"placeholder = "descrabtion"required/>  

<div class="row">
    <div class="form-group col-md-3">
<label > Price in JOD </label >  
<input class = "form-control price-group "  type = "text" name = "priceJod" value = "<?=$book1['priceJod']?>" placeholder = "priceJod" />    
</div>
    <div class="form-group col-md-3">
<label > Price in USD </label >  
<input class = "form-control price-group" type = "text" name = "priceUsd" value = "<?=$book1['priceUsd']?>" placeholder = "priceUsd" />      
</div>
    <div class="form-group col-md-3">
<label > Price in ERU </label >  
<input class = "form-control price-group" type = "text" name = "priceEru" value = "<?=$book1['priceEru']?>" placeholder = "priceEru" /> 
  </div>

</div>

<div class="row">
  <div class="form-group col-md-5">
      <label > start Date </label >  
        <input class="form-control startDate_edit"  type="text" name="startDate" value = "<?=$book1['startDate']?>"    autocomplete="fales" />
  <span class="input-group-addon ">
                        <span class="glyphicon glyphicon-calendar "></span>
                    </span>
  </div>

  <div class="form-group col-md-5">
      <label > end Date </label >  
        <input class="form-control endDate_edit"  type="text" name="endDate" value = "<?=$book1['endDate']?>" autocomplete="fales" />
  <span class="input-group-addon ">
                        <span class="glyphicon glyphicon-calendar "></span>
                    </span>
      </div>

</div>

  <?php
}?>




</body>
</html>




